const superPowers = {
  D: [
    "Night Vision",
    "Enhanced Reflexes",
    "Underwater Breathing",
    "Animal Communication",
    "Plant Growth",
    "Fire Resistance",
    "Low-Level Telepathy",
    "Enhanced Jump",
    "Pain Suppression",
    "Magnetic Manipulation",
    "Thermal Resistance",
    "Electric Shock",
    "Glow in the Dark",
    "Silent Movement",
    "Water Walking",
    "Quick Healing",
    "Venom Resistance",
    "Enhanced Digging",
    "Slow Aging",
    "Fog Creation",
    "Glass Manipulation",
    "Paper Manipulation",
    "Enhanced Smell",
    "Lightweight Body",
    "Surface Adhesion",
  ],
  C: [
    "Invisibility",
    "Telekinesis",
    "Energy Shields",
    "Enhanced Agility",
    "Sound Manipulation",
    "Ice Manipulation",
    "Heat Vision",
    "Acid Spit",
    "Wall Crawling",
    "Camouflage",
    "Elasticity",
    "Memory Manipulation",
    "Wind Manipulation",
    "Sand Manipulation",
    "Superhuman Accuracy",
    "Hypnosis",
    "Poison Generation",
    "Metal Manipulation",
    "Solar Energy Absorption",
    "Probability Manipulation",
    "Portal Creation",
    "Lunar Empowerment",
    "Vibration Control",
    "Oxygen Independence",
    "Flash Freezing",
  ],
  B: [
    "Flight",
    "Super Strength",
    "Laser Vision",
    "Teleportation",
    "Time Pause",
    "Electrokinesis",
    "Fire Manipulation",
    "Super Speed",
    "Phasing",
    "Force Field",
    "Gravity Manipulation",
    "Time Manipulation",
    "Superhuman Intelligence",
    "Regeneration",
    "Duplication",
    "Size Manipulation",
    "Spectral Vision",
    "Plasma Manipulation",
    "Seismic Power",
    "Life Force Absorption",
    "Animal Morphing",
    "Sound Wave Generation",
    "Matter Ingestion",
    "Aura Manipulation",
    "Darkness Manipulation",
  ],
  A: [
    "Shape Shifting",
    "Weather Control",
    "Mind Reading",
    "Healing",
    "Dimensional Travel",
    "Gravity Control",
    "Temporal Rewind",
    "Energy Conversion",
    "Soul Manipulation",
    "Reality Bending",
    "Molecular Manipulation",
    "Quantum Manipulation",
    "Astral Projection",
    "Advanced Telekinesis",
    "Precognition",
    "Bioluminescence",
    "Psychic Surgery",
    "Force Field Bubble",
    "Nuclear Manipulation",
    "Advanced Illusion Casting",
    "Cosmic Awareness",
    "Perpetual Energy",
    "Omnilingualism",
    "Advanced Stealth",
    "Enhanced Invention",
  ],
  S: [
    "Reality Warping",
    "Time Travel",
    "Cosmic Energy Manipulation",
    "Omnipotence",
    "Resurrection",
    "Absolute Invulnerability",
    "Universal Manipulation",
    "Multidimensional Manipulation",
    "Chronokinesis",
    "Absolute Strength",
    "Omniscience",
    "Infinite Creation",
    "Unlimited Manipulation",
    "Existence Erasure",
    "Immortality",
    "Metaphysical Liberation",
    "Infinite Intelligence",
    "True Invisibility",
    "Boundless Inner World",
    "Supreme Teleportation",
    "All-Powerful Psychokinesis",
    "Singularity",
    "Non-Corporeal Form",
    "Dimensional Omnipresence",
    "Ultimate Invincibility",
  ],
};
function getRandomPower(rank) {
  if (superPowers[rank]) {
    const powers = superPowers[rank];
    const randomIndex = Math.floor(Math.random() * powers.length);
    return powers[randomIndex];
  } else {
    return "Invalid rank";
  }
}

// Example usage
console.log(getRandomPower("B")); // Might print any power from B class
console.log(getRandomPower("S"));
